### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by andrewisen-tikab** [andrewisen-tikab/sej#83]
- [ ] Wait for THREE.js to better support WebGPU
- [x] Test in production
- [ ] Update docs
- [ ] Add zod schemas
- [ ] Add unit testing
